### ISSUE TITLE
Export GOFED_DEVEL=1 with setup.py installation

### ISSUE THREAD

**Issue by fridex** [gofed/lib#10]
There needs to be exported GOFED_DEVEL variable in order to run gofedlib-cli introduced in https://github.com/gofed/lib/pull/9. It would be nice to get rid of that.

**Comment by ingvagabund** [comment]
This is needed to run the gofed from local configuration files.

**Comment by ingvagabund** [comment]
Can you open this PR for gofedlib?

**Comment by fridex** [comment]
I will open it threre, closing here.
