### ISSUE TITLE
Failed to parse github.com/mattn/go-sqlite3 5e6658a master

### ISSUE THREAD

**Issue by fridex** [gofed/lib#6]
When scanning deps in `github.com/mattn/go-sqlite3`, commit 5e6658a (master), I get following error:

```
ExtractionError: Error parsing /github.com-mattn-go-sqlite3-5e6658a-master/sqlite3_test.go: 2016/04/20 19:54:02 github.com-mattn-go-sqlite3-5e6658a-master/sqlite3_test.go:748:12: expected operand, found := (and 1 more errors)
```

Is this error expected?

**Comment by ingvagabund** [comment]
Check out the file it fails on. Most likely, the sqlite3_test.go is not valid go code.

**Comment by fridex** [comment]
There is a syntax error, propagated error is correct.

**Comment by ingvagabund** [comment]
The error is generated by the go parser itself. I am just picking the error message and forwarding up.
